name: Pentoo Binpkg Check

on:
  schedule:
    - cron: "6 * * * *"
  pull_request:
    branches:
      - master

jobs:
  pentoo-visibility-check:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: List added files
      run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}
    -
      name: Binpkg Check
      run: |
        sudo docker build --progress=plain . -f scripts/qa/Dockerfile.binpkg
