name: Pentoo Build Test

on:
  pull_request:
    branches:
      - master

jobs:
  pentoo-build-test:
    runs-on: ubuntu-latest
    steps:
    -
      name: df1
      run: df -h
    -
      name: Cleanup worker diskspace
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo docker builder prune -a
    -
      name: df2
      run: df -h
    -
      name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: List added files
      run: git --no-pager diff --name-only "$(git rev-parse --verify origin/master 2> /dev/null)" HEAD
    -
      name: Pentoo Build Test
      run: |
        sudo docker build --progress=plain . -f scripts/qa/Dockerfile.build
